'use strict';

//~~** This file is auto generated by tools, please DO NOT EDIT it. **~~

Object.defineProperty(exports, '__esModule', { value: true });

var cloud_1 = require('wx-server-sdk');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var cloud_1__default = /*#__PURE__*/_interopDefaultLegacy(cloud_1);

function tryParseJson(json, defaultValue) {
    try {
        return JSON.parse(json);
    }
    catch {
        return defaultValue;
    }
}

const default_1 = async () => {
    const wxContext = cloud_1__default["default"].getWXContext();
    const json = tryParseJson('{"a": 1, "b": 2, "c": 3}', { a: 8 });
    const number = await Promise.resolve(1);
    return {
        openid: wxContext.OPENID,
        appid: wxContext.APPID,
        unionid: wxContext.UNIONID,
        env: wxContext.ENV,
        wxContext,
        json,
        number
    };
};
cloud_1__default["default"].init({ env: cloud_1__default["default"].DYNAMIC_CURRENT_ENV });
async function main(event) {
    return default_1();
}

exports.main = main;
//# sourceMappingURL=index.js.map
