'use strict';

//~~** This file is auto generated by tools, please DO NOT EDIT it. **~~

Object.defineProperty(exports, '__esModule', { value: true });

var util = require('util');
var cloud_1 = require('wx-server-sdk');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var cloud_1__default = /*#__PURE__*/_interopDefaultLegacy(cloud_1);

function tryParseJson(json, defaultValue) {
    try {
        return JSON.parse(json);
    }
    catch {
        return defaultValue;
    }
}

const default_1 = (object) => {
    const json = tryParseJson('{"a": 1, "b": 2}', { a: 8 });
    return util.formatWithOptions({ depth: 6 }, { object, json });
};
cloud_1__default["default"].init({ env: cloud_1__default["default"].DYNAMIC_CURRENT_ENV });
async function main(event) {
    return default_1(event.object);
}

exports.main = main;
//# sourceMappingURL=index.js.map
