'use strict';

//~~** This file is auto generated by tools, please DO NOT EDIT it. **~~

Object.defineProperty(exports, '__esModule', { value: true });

var cloud_1 = require('wx-server-sdk');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var cloud_1__default = /*#__PURE__*/_interopDefaultLegacy(cloud_1);

const default_1 = (a, b) => {
    return a + b;
};
cloud_1__default["default"].init({ env: cloud_1__default["default"].DYNAMIC_CURRENT_ENV });
async function main(event) {
    return default_1(event.a, event.b);
}

exports.main = main;
//# sourceMappingURL=index.js.map
